### PR TITLE
Created preprod YAML files and updated references

### PR DESCRIPTION
**Pull request by nickvholbrook**
Added ALZ pre-prod settings as part of on-boarding process.

### CODE REVIEW

**Review by wanieldilson — COMMENTED** [review]
Hi Nick,  This all looks good.  One final change I didn't mention.  Please add an additional scrape target in[ prometheus-configmap.yml line 46](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/blob/5f9effec51640ce8be8050f88173522c2c888f54/kubernetes/infrastructure-monitoring/templates/prometheus-configmap.yaml#L46)

You can copy the one used for devl.

**Comment by nickvholbrook** [comment]
Hi Dan,

Would that be as below with the same port number?

            - '{{ .Release.Name }}-azure-preprod-metrics-exporter:9276'

**Comment by wanieldilson** [comment]
> Hi Dan,
> 
> Would that be as below with the same port number?
> 
> ```
>         - '{{ .Release.Name }}-azure-preprod-metrics-exporter:9276'
> ```

Exactly right, you can confirm the port [here ](https://github.com/ministryofjustice/staff-infrastructure-monitoring-deployments/pull/21/files#diff-795a443daa0d8f3a7fd12e132f3c66c9fe6eb02ac852e4c282882acbdfee3599R24) also

**Review by wanieldilson — APPROVED** [review]
LGTM

**Pull request merged**
